"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
class ErrorCommonData {
}
ErrorCommonData.COM001 = 'You have no permission to retrieve this information!';
ErrorCommonData.COM002 = 'Router must have request handler function!';
ErrorCommonData.COM003 = 'Bad request!';
ErrorCommonData.COM004 = 'The password must have atleast 8 chars with one uppercase letter, one lower case letter, one digit and one special character!';
ErrorCommonData.COM005 = 'Unauthorized';
ErrorCommonData.COM006 = 'Forbidden';
ErrorCommonData.COM007 = 'Not found';
ErrorCommonData.COM008 = 'Method not Aalowed';
ErrorCommonData.COM009 = 'Request timeout';
ErrorCommonData.COM010 = 'Server lost connection!';
ErrorCommonData.COM101 = '{0} is invalid!';
ErrorCommonData.COM102 = '{0} is not exists!';
ErrorCommonData.COM103 = '{0} is not updated!';
ErrorCommonData.COM104 = '{0} is already existed!';
ErrorCommonData.COM105 = '{0} is required!';
ErrorCommonData.COM106 = '{0} is not ready!';
ErrorCommonData.COM107 = '{0} is not connected yet!';
ErrorCommonData.COM108 = '{0} is incorrect!';
ErrorCommonData.COM109 = '{0} is not activated!';
ErrorCommonData.COM110 = '{0} is canceled!';
ErrorCommonData.COM111 = '{0} is not available!';
ErrorCommonData.COM112 = '{0} is not found!';
ErrorCommonData.COM113 = '{0} has failed!';
ErrorCommonData.COM114 = '{0} is missing!';
ErrorCommonData.COM201 = 'Minimum {0} is {1} characters!';
ErrorCommonData.COM202 = 'Maximum {0} is {1} characters!';
ErrorCommonData.COM203 = '{0} is greater than {1}!';
exports.default = ErrorCommonData;
;
