import AbnBusiness from '../app/business/AbnBusiness';
import IAbnBusiness from '../app/business/interfaces/IAbnBusiness';
// import AccountingBusiness from '../app/business/AccountingBusiness';
import IAccountingBusiness from '../app/business/interfaces/IAccountingBusiness';
import ChartAccountBusiness from '../app/business/ChartAccountBusiness';
import IChartAccountBusiness from '../app/business/interfaces/IChartAccountBusiness';
import ChartAccountAssignmentBusiness from '../app/business/ChartAccountAssignmentBusiness';
import IChartAccountAssignmentBusiness from '../app/business/interfaces/IChartAccountAssignmentBusiness';
import CrunchBusiness from '../app/business/CrunchBusiness';
import ICrunchBusiness from '../app/business/interfaces/ICrunchBusiness';
import FileBusiness from '../app/business/FileBusiness';
import IFileBusiness from '../app/business/interfaces/IFileBusiness';
// import FinanceBusiness from '../app/business/FinanceBusiness';
import IFinanceBusiness from '../app/business/interfaces/IFinanceBusiness';
import GroupExpenseBusiness from '../app/business/GroupExpenseBusiness';
import IGroupExpenseBusiness from '../app/business/interfaces/IGroupExpenseBusiness';
import ManagerBusiness from '../app/business/ManagerBusiness';
import IManagerBusiness from '../app/business/interfaces/IManagerBusiness';
// import ReceiptBusiness from '../app/business/ReceiptBusiness';
import IReceiptBusiness from '../app/business/interfaces/IReceiptBusiness';
import RoleBusiness from '../app/business/RoleBusiness';
import IRoleBusiness from '../app/business/interfaces/IRoleBusiness';
import StatementBusiness from '../app/business/StatementBusiness';
import IStatementBusiness from '../app/business/interfaces/IStatementBusiness';
// import StripeBusiness from '../app/business/StripeBusiness';
import IStripeBusiness from '../app/business/interfaces/IStripeBusiness';
import TransactionBusiness from '../app/business/TransactionBusiness';
import ITransactionBusiness from '../app/business/interfaces/ITransactionBusiness';
import UserBusiness from '../app/business/UserBusiness';
import IUserBusiness from '../app/business/interfaces/IUserBusiness';
import YodleeBusiness from '../app/business/YodleeBusiness';
import IYodleeBusiness from '../app/business/interfaces/IYodleeBusiness';
import ProductBusiness from '../app/business/ProductBusiness';
import IProductBusiness from '../app/business/interfaces/IProductBusiness';
import BudgetBusiness from '../app/business/BudgetBusiness';
import IBudgetBusiness from '../app/business/interfaces/IBudgetBusiness';
import MessageBusiness from '../app/business/MessageBusiness';
import IMessageBusiness from '../app/business/interfaces/IMessageBusiness';
import ISettingReportBusiness from '../app/business/interfaces/ISettingReportBusiness';
import SettingReportBusiness from '../app/business/SettingReportBusiness';
import IGeneralJournalBusiness from '../app/business/interfaces/IGeneralJournalBusiness';
import GeneralJournalBusiness from '../app/business/GeneralJournalBusiness';
import ConnectBankBusiness from '../app/business/ConnectBankBusiness';
import IConnectBankBusiness from '../app/business/interfaces/IConnectBankBusiness';

class BusinessLoader {
    static abnBusiness: IAbnBusiness;
    static accountingBusiness: IAccountingBusiness;
    static chartAccountBusiness: IChartAccountBusiness;
    static chartAccountAssignmentBusiness: IChartAccountAssignmentBusiness;
    static fileBusiness: IFileBusiness;
    static financeBusiness: IFinanceBusiness;
    static groupExpenseBusiness: IGroupExpenseBusiness;
    static managerBusiness: IManagerBusiness;
    static receiptBusiness: IReceiptBusiness;
    static roleBusiness: IRoleBusiness;
    static statementBusiness: IStatementBusiness;
    static stripeBusiness: IStripeBusiness;
    static transactionBusiness: ITransactionBusiness;
    static userBusiness: IUserBusiness;
    static yodleeBusiness: IYodleeBusiness;
    static productBusiness: IProductBusiness;
    static budgetBusiness: IBudgetBusiness;
    static crunchBusiness:ICrunchBusiness;
    static messageBusiness:IMessageBusiness;
    static settingReportBusiness:ISettingReportBusiness;
    static generalJournalBusiness:IGeneralJournalBusiness;
    static connectBankBusiness:IConnectBankBusiness;

    static init() {
        BusinessLoader.abnBusiness = new AbnBusiness();
        // BusinessLoader.accountingBusiness = new AccountingBusiness();
        BusinessLoader.chartAccountBusiness = new ChartAccountBusiness();
        BusinessLoader.chartAccountAssignmentBusiness = new ChartAccountAssignmentBusiness();
        BusinessLoader.fileBusiness = new FileBusiness();
        // BusinessLoader.financeBusiness = new FinanceBusiness();
        BusinessLoader.groupExpenseBusiness = new GroupExpenseBusiness();
        BusinessLoader.managerBusiness = new ManagerBusiness();
        // BusinessLoader.receiptBusiness = new ReceiptBusiness();
        BusinessLoader.roleBusiness = new RoleBusiness();
        BusinessLoader.statementBusiness = new StatementBusiness();
        // BusinessLoader.stripeBusiness = new StripeBusiness();
        BusinessLoader.transactionBusiness = new TransactionBusiness();
        BusinessLoader.userBusiness = new UserBusiness();
        BusinessLoader.productBusiness = new ProductBusiness();
        BusinessLoader.yodleeBusiness = new YodleeBusiness();
        BusinessLoader.budgetBusiness = new BudgetBusiness();
        BusinessLoader.crunchBusiness = new CrunchBusiness();
        BusinessLoader.messageBusiness = new MessageBusiness();
        BusinessLoader.settingReportBusiness = new SettingReportBusiness();
        BusinessLoader.generalJournalBusiness = new GeneralJournalBusiness();
        BusinessLoader.connectBankBusiness = new ConnectBankBusiness();
    }
}

export default BusinessLoader;
