import ITransaction from './interfaces/ITransaction';
import { BankType, CrunchType } from '../common/CommonType';
declare class Transaction {
    _id: string;
    amount: any;
    accountId: number;
    baseType: string;
    bankId: number;
    categoryType: string;
    categoryId: number;
    category: string;
    categorySource: string;
    description: any;
    date: Date;
    highLevelCategoryId: number;
    isManual: boolean;
    isWarningDuplicate?: boolean;
    duplicateId?: string;
    merchant: any;
    postDate?: Date;
    runningBalance: any;
    status: string;
    transactionId: number;
    userId: any;
    type: BankType;
    typeCrunch: CrunchType;
    month: number;
    year: number;
    coaId: any;
    index?: number;
    conditions: any;
    manualTransaction?: boolean;
    constructor(model: ITransaction);
    static parseArray(list: ITransaction[]): Transaction[];
    static parseObjectByCrunch(list: ITransaction[]): Object;
}
export default Transaction;
