import module from 'justdone-system-package/dest/resources/permission/module';
import {RoleCode} from 'justdone-system-package/dest/app/model/common/CommonType';

export function getPermissions(): {claim: number, fromRole: number, toRole: number | null}[] {
    return [
        {claim: module.SYSTEM.claim.ACCESS.code, fromRole: RoleCode.ProductAdmin, toRole: null},
        {claim: module.SYSTEM.claim.ACCESS.code, fromRole: RoleCode.Client, toRole: null},
        {claim: module.SYSTEM.claim.ACCESS.code, fromRole: RoleCode.ProductManager, toRole: null},

        {claim: module.PRODUCT.claim.GET.code, fromRole: RoleCode.SuperAdmin, toRole: null},
        {claim: module.PRODUCT.claim.GET.code, fromRole: RoleCode.RegionAdmin, toRole: null},
        {claim: module.PRODUCT.claim.GET.code, fromRole: RoleCode.Supervisor, toRole: null},
        {claim: module.PRODUCT.claim.GET.code, fromRole: RoleCode.CaseManager, toRole: null},
        {claim: module.PRODUCT.claim.GET.code, fromRole: RoleCode.ProductAdmin, toRole: RoleCode.Client},
        {claim: module.PRODUCT.claim.GET.code, fromRole: RoleCode.Client, toRole: null},
        {claim: module.PRODUCT.claim.GET.code, fromRole: RoleCode.ProductManager, toRole: RoleCode.Client},
        {claim: module.PRODUCT.claim.GET.code, fromRole: RoleCode.ProductManager, toRole: null},
        {claim: module.PRODUCT.claim.GET.code, fromRole: RoleCode.ProductAdmin, toRole: RoleCode.ProductManager},
        {claim: module.PRODUCT.claim.GET.code, fromRole: RoleCode.ProductAdmin, toRole: null},
        {claim: module.PRODUCT.claim.UPDATE.code, fromRole: RoleCode.ProductAdmin, toRole: null},

        {claim: module.ROLE.claim.GET.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.ProductAdmin},
        {claim: module.ROLE.claim.GET.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.ProductManager},
        {claim: module.ROLE.claim.GET.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Client},
        {claim: module.ROLE.claim.GET.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.ProductAdmin},
        {claim: module.ROLE.claim.GET.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.ProductManager},
        {claim: module.ROLE.claim.GET.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.Client},
        {claim: module.ROLE.claim.GET.code, fromRole: RoleCode.CaseManager, toRole: RoleCode.Client},
        {claim: module.ROLE.claim.GET.code, fromRole: RoleCode.ProductAdmin, toRole: RoleCode.ProductManager},
        {claim: module.ROLE.claim.GET.code, fromRole: RoleCode.ProductAdmin, toRole: RoleCode.Client},
        {claim: module.ROLE.claim.GET.code, fromRole: RoleCode.ProductManager, toRole: RoleCode.Client},

        {claim: module.MANAGER.claim.GET.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.ProductAdmin},
        {claim: module.MANAGER.claim.GET.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.ProductManager},
        {claim: module.MANAGER.claim.GET.code, fromRole: RoleCode.ProductAdmin, toRole: RoleCode.ProductManager},
        {claim: module.MANAGER.claim.GET.code, fromRole: RoleCode.ProductAdmin, toRole: RoleCode.Supervisor},
        {claim: module.MANAGER.claim.GET.code, fromRole: RoleCode.ProductManager, toRole: RoleCode.Supervisor},
        {claim: module.MANAGER.claim.GET_MANAGER_FOR_ASSIGN.code, fromRole: RoleCode.ProductAdmin, toRole: RoleCode.ProductManager},
        {claim: module.MANAGER.claim.GET_CLIENT.code, fromRole: RoleCode.ProductAdmin, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.GET_CLIENT.code, fromRole: RoleCode.ProductManager, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.GET_CLIENT.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.GET_CLIENT.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.GET_CLIENT.code, fromRole: RoleCode.CaseManager, toRole: RoleCode.Client},
        // {claim: module.MANAGER.claim.GET_CLIENT.code, fromRole: RoleCode.ProductManager, toRole: RoleCode.Client},
        // {claim: module.MANAGER.claim.GET_CLIENT.code, fromRole: RoleCode.ProductAdmin, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.GET_CLIENT.code, fromRole: RoleCode.Supervisor, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.GET_CLIENT_BY_MANAGER.code, fromRole: RoleCode.ProductAdmin, toRole: RoleCode.ProductManager},
        {claim: module.MANAGER.claim.GET_CLIENT_PERSONAL_INFO.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.GET_CLIENT_PERSONAL_INFO.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.GET_CLIENT_PERSONAL_INFO.code, fromRole: RoleCode.Supervisor, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.GET_CLIENT_PERSONAL_INFO.code, fromRole: RoleCode.CaseManager, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.GET_CLIENT_PERSONAL_INFO.code, fromRole: RoleCode.ProductAdmin, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.GET_CLIENT_PERSONAL_INFO.code, fromRole: RoleCode.ProductAdmin, toRole: null},
        {claim: module.MANAGER.claim.GET_CLIENT_PERSONAL_INFO.code, fromRole: RoleCode.ProductManager, toRole: null},
        {claim: module.MANAGER.claim.GET_CLIENT_PERSONAL_INFO.code, fromRole: RoleCode.ProductManager, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.GET_CLIENT_BUSINESS_INFO.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.GET_CLIENT_BUSINESS_INFO.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.GET_CLIENT_BUSINESS_INFO.code, fromRole: RoleCode.CaseManager, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.GET_CLIENT_BUSINESS_INFO.code, fromRole: RoleCode.Supervisor, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.GET_CLIENT_BUSINESS_INFO.code, fromRole: RoleCode.ProductAdmin, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.GET_CLIENT_BUSINESS_INFO.code, fromRole: RoleCode.ProductManager, toRole: null},
        {claim: module.MANAGER.claim.GET_CLIENT_BUSINESS_INFO.code, fromRole: RoleCode.ProductManager, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.GET_CLIENT_BUSINESS_INFO.code, fromRole: RoleCode.ProductAdmin, toRole: null},
        {claim: module.MANAGER.claim.GET_CLIENT_CONNECTED_BANK.code, fromRole: RoleCode.ProductManager, toRole: null},
        {claim: module.MANAGER.claim.GET_CLIENT_CONNECTED_BANK.code, fromRole: RoleCode.ProductAdmin, toRole: null},
        {claim: module.MANAGER.claim.GET_CLIENT_CONNECTED_BANK.code, fromRole: RoleCode.ProductManager, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.GET_CLIENT_CONNECTED_BANK.code, fromRole: RoleCode.ProductAdmin, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.GET_CLIENT_TRADING_QUESTION.code, fromRole: RoleCode.ProductManager, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.GET_CLIENT_TRADING_QUESTION.code, fromRole: RoleCode.ProductAdmin, toRole: null},
        {claim: module.MANAGER.claim.GET_CLIENT_TRADING_QUESTION.code, fromRole: RoleCode.ProductManager, toRole: null},
        {claim: module.MANAGER.claim.GET_CLIENT_TRADING_QUESTION.code, fromRole: RoleCode.ProductAdmin, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.CREATE.code, fromRole: RoleCode.ProductAdmin, toRole: RoleCode.ProductManager},
        {claim: module.MANAGER.claim.CREATE.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.ProductAdmin},
        {claim: module.MANAGER.claim.CREATE.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.ProductManager},
        // {claim: module.MANAGER.claim.CREATE.code, fromRole: RoleCode.ProductAdmin, toRole: null},
        {claim: module.MANAGER.claim.CREATE_CLIENT.code, fromRole: RoleCode.ProductAdmin, toRole: null},
        {claim: module.MANAGER.claim.CREATE_CLIENT.code, fromRole: RoleCode.SuperAdmin, toRole: null},
        {claim: module.MANAGER.claim.CREATE_CLIENT.code, fromRole: RoleCode.RegionAdmin, toRole: null},
        {claim: module.MANAGER.claim.CREATE_CLIENT.code, fromRole: RoleCode.Supervisor, toRole: null},
        {claim: module.MANAGER.claim.UPDATE.code, fromRole: RoleCode.ProductAdmin, toRole: null},
        {claim: module.MANAGER.claim.UPDATE.code, fromRole: RoleCode.ProductAdmin, toRole: RoleCode.ProductManager},
        {claim: module.MANAGER.claim.UPDATE.code, fromRole: RoleCode.ProductManager, toRole: null},
        {claim: module.MANAGER.claim.UPDATE.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.ProductAdmin},
        {claim: module.MANAGER.claim.UPDATE.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.ProductManager},
        {claim: module.MANAGER.claim.UPDATE_CLIENT.code, fromRole: RoleCode.ProductAdmin, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.UPDATE_CLIENT.code, fromRole: RoleCode.ProductManager, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.UPDATE_CLIENT.code, fromRole: RoleCode.ProductManager, toRole: null},
        {claim: module.MANAGER.claim.UPDATE_CLIENT.code, fromRole: RoleCode.ProductAdmin, toRole: null},
        // {claim: module.MANAGER.claim.UPDATE_CLIENT_PERSONAL_INFO.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Client},
        // {claim: module.MANAGER.claim.UPDATE_CLIENT_PERSONAL_INFO.code, fromRole: RoleCode.ProductManager, toRole: RoleCode.Client},
        // {claim: module.MANAGER.claim.UPDATE_CLIENT_PERSONAL_INFO.code, fromRole: RoleCode.ProductAdmin, toRole: RoleCode.Client},
        // {claim: module.MANAGER.claim.UPDATE_CLIENT_PERSONAL_INFO.code, fromRole: RoleCode.ProductManager, toRole: null},
        // {claim: module.MANAGER.claim.UPDATE_CLIENT_PERSONAL_INFO.code, fromRole: RoleCode.ProductAdmin, toRole: null},
        // {claim: module.MANAGER.claim.UPDATE_CLIENT_BUSINESS_INFO.code, fromRole: RoleCode.ProductAdmin, toRole: RoleCode.Client},
        // {claim: module.MANAGER.claim.UPDATE_CLIENT_BUSINESS_INFO.code, fromRole: RoleCode.ProductManager, toRole: null},
        // {claim: module.MANAGER.claim.UPDATE_CLIENT_BUSINESS_INFO.code, fromRole: RoleCode.ProductAdmin, toRole: null},
        // {claim: module.MANAGER.claim.UPDATE_CLIENT_BUSINESS_INFO.code, fromRole: RoleCode.ProductManager, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.UPDATE_CLIENT_CONNECTED_BANK.code, fromRole: RoleCode.ProductManager, toRole: null},
        {claim: module.MANAGER.claim.UPDATE_CLIENT_CONNECTED_BANK.code, fromRole: RoleCode.ProductAdmin, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.UPDATE_CLIENT_CONNECTED_BANK.code, fromRole: RoleCode.ProductManager, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.UPDATE_CLIENT_CONNECTED_BANK.code, fromRole: RoleCode.ProductAdmin, toRole: null},
        {claim: module.MANAGER.claim.UPDATE_CLIENT_RECONNECT_BANK.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.UPDATE_CLIENT_RECONNECT_BANK.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.UPDATE_CLIENT_RECONNECT_BANK.code, fromRole: RoleCode.Supervisor, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.UPDATE_CLIENT_RECONNECT_BANK.code, fromRole: RoleCode.CaseManager, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.UPDATE_CLIENT_TRADING_QUESTION.code, fromRole: RoleCode.ProductManager, toRole: null},
        {claim: module.MANAGER.claim.UPDATE_CLIENT_TRADING_QUESTION.code, fromRole: RoleCode.ProductAdmin, toRole: null},
        {claim: module.MANAGER.claim.DELETE.code, fromRole: RoleCode.ProductAdmin, toRole: null},
        {claim: module.MANAGER.claim.DELETE.code, fromRole: RoleCode.ProductAdmin, toRole: RoleCode.ProductManager},
        {claim: module.MANAGER.claim.DELETE_CLIENT.code, fromRole: RoleCode.ProductAdmin, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.DELETE_CLIENT.code, fromRole: RoleCode.ProductAdmin, toRole: null},
        {claim: module.MANAGER.claim.DELETE_CLIENT.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Client},

        {claim: module.CHART_OF_ACCOUNT.claim.GET.code, fromRole: RoleCode.ProductAdmin, toRole: null},
        {claim: module.CHART_OF_ACCOUNT.claim.GET.code, fromRole: RoleCode.SuperAdmin, toRole: null},
        {claim: module.CHART_OF_ACCOUNT.claim.GET.code, fromRole: RoleCode.RegionAdmin, toRole: null},
        {claim: module.CHART_OF_ACCOUNT.claim.GET.code, fromRole: RoleCode.Supervisor, toRole: null},
        {claim: module.CHART_OF_ACCOUNT.claim.GET.code, fromRole: RoleCode.CaseManager, toRole: null},
        {claim: module.CHART_OF_ACCOUNT.claim.ASSIGN_CLIENT.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Client},

        {claim: module.USER.claim.GET.code, fromRole: RoleCode.Client, toRole: null},
        {claim: module.USER.claim.UPDATE.code, fromRole: RoleCode.Client, toRole: null},

        // {claim: module.GROUP_EXPENSE.claim.GET.code, fromRole: RoleCode.ProductManager, toRole: null},
        {claim: module.GROUP_EXPENSE.claim.GET.code, fromRole: RoleCode.ProductAdmin, toRole: null},
        // {claim: module.GROUP_EXPENSE.claim.GET.code, fromRole: RoleCode.Client, toRole: null},
        {claim: module.GROUP_EXPENSE.claim.CREATE.code, fromRole: RoleCode.ProductAdmin, toRole: null},
        {claim: module.GROUP_EXPENSE.claim.UPDATE.code, fromRole: RoleCode.ProductAdmin, toRole: null},
        {claim: module.GROUP_EXPENSE.claim.DELETE.code, fromRole: RoleCode.ProductAdmin, toRole: null},

        {claim: module.CHART_OF_ACCOUNT.claim.GET.code, fromRole: RoleCode.ProductAdmin, toRole: null},
        {claim: module.CHART_OF_ACCOUNT.claim.GET.code, fromRole: RoleCode.SuperAdmin, toRole: null},
        {claim: module.CHART_OF_ACCOUNT.claim.GET.code, fromRole: RoleCode.RegionAdmin, toRole: null},
        {claim: module.CHART_OF_ACCOUNT.claim.GET.code, fromRole: RoleCode.Supervisor, toRole: null},
        {claim: module.CHART_OF_ACCOUNT.claim.GET.code, fromRole: RoleCode.CaseManager, toRole: null},
        // {claim: module.CHART_OF_ACCOUNT.claim.GET.code, fromRole: RoleCode.Client, toRole: null},
        // {claim: module.CHART_OF_ACCOUNT.claim.GET.code, fromRole: RoleCode.ProductManager, toRole: null},
        {claim: module.CHART_OF_ACCOUNT.claim.ASSIGN_CLIENT.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Client},

        {claim: module.STATEMENT.claim.GET.code, fromRole: RoleCode.Client, toRole: null},
        {claim: module.STATEMENT.claim.GET.code, fromRole: RoleCode.ProductManager, toRole: RoleCode.Client},
        {claim: module.STATEMENT.claim.GET.code, fromRole: RoleCode.ProductAdmin, toRole: RoleCode.Client},
        {claim: module.STATEMENT.claim.GET.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Client},
        {claim: module.STATEMENT.claim.GET.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.Client},
        {claim: module.STATEMENT.claim.GET.code, fromRole: RoleCode.Supervisor, toRole: RoleCode.Client},
        {claim: module.STATEMENT.claim.GET.code, fromRole: RoleCode.CaseManager, toRole: RoleCode.Client},
        {claim: module.STATEMENT.claim.UPDATE.code, fromRole: RoleCode.Client, toRole: null},
        {claim: module.STATEMENT.claim.UPDATE.code, fromRole: RoleCode.ProductAdmin, toRole: RoleCode.Client},
        {claim: module.STATEMENT.claim.UPDATE.code, fromRole: RoleCode.ProductManager, toRole: RoleCode.Client},

        {claim: module.TRANSACTION.claim.GET.code, fromRole: RoleCode.Client, toRole: null},
        {claim: module.TRANSACTION.claim.GET.code, fromRole: RoleCode.ProductAdmin, toRole: RoleCode.Client},
        {claim: module.TRANSACTION.claim.GET.code, fromRole: RoleCode.ProductManager, toRole: RoleCode.Client},
        {claim: module.TRANSACTION.claim.GET.code, fromRole: RoleCode.CaseManager, toRole: RoleCode.Client},
        {claim: module.TRANSACTION.claim.GET.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Client},
        {claim: module.TRANSACTION.claim.GET.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.Client},
        {claim: module.TRANSACTION.claim.GET.code, fromRole: RoleCode.Supervisor, toRole: RoleCode.Client},
        {claim: module.TRANSACTION.claim.UPDATE.code, fromRole: RoleCode.CaseManager, toRole: RoleCode.Client},

        {claim: module.PROVIDER.claim.GET.code, fromRole: RoleCode.ProductAdmin, toRole: RoleCode.Client},
        {claim: module.PROVIDER.claim.GET.code, fromRole: RoleCode.ProductManager, toRole: RoleCode.Client},
        {claim: module.PROVIDER.claim.GET.code, fromRole: RoleCode.Client, toRole: null},

        {claim: module.RECEIPT.claim.GET.code, fromRole: RoleCode.ProductManager, toRole: RoleCode.Client},
        {claim: module.RECEIPT.claim.GET.code, fromRole: RoleCode.Client, toRole: null},
        {claim: module.RECEIPT.claim.GET.code, fromRole: RoleCode.ProductAdmin, toRole: RoleCode.Client},
        {claim: module.RECEIPT.claim.CREATE.code, fromRole: RoleCode.Client, toRole: null},
        {claim: module.RECEIPT.claim.CREATE.code, fromRole: RoleCode.ProductManager, toRole: RoleCode.Client},
        {claim: module.RECEIPT.claim.CREATE.code, fromRole: RoleCode.ProductAdmin, toRole: RoleCode.Client},
        {claim: module.RECEIPT.claim.UPDATE.code, fromRole: RoleCode.ProductManager, toRole: RoleCode.Client},
        {claim: module.RECEIPT.claim.UPDATE.code, fromRole: RoleCode.Client, toRole: null},
        {claim: module.RECEIPT.claim.UPDATE.code, fromRole: RoleCode.ProductAdmin, toRole: RoleCode.Client},
        {claim: module.RECEIPT.claim.DELETE.code, fromRole: RoleCode.ProductAdmin, toRole: RoleCode.Client},
        {claim: module.RECEIPT.claim.DELETE.code, fromRole: RoleCode.Client, toRole: null},
        {claim: module.RECEIPT.claim.DELETE.code, fromRole: RoleCode.ProductManager, toRole: RoleCode.Client},

        {claim: module.FINANCIAL.claim.GET.code, fromRole: RoleCode.ProductAdmin, toRole: RoleCode.Client},
        {claim: module.FINANCIAL.claim.GET.code, fromRole: RoleCode.Client, toRole: null},
        {claim: module.FINANCIAL.claim.GET.code, fromRole: RoleCode.ProductManager, toRole: RoleCode.Client},
        {claim: module.FINANCIAL.claim.CREATE.code, fromRole: RoleCode.ProductAdmin, toRole: RoleCode.Client},
        {claim: module.FINANCIAL.claim.CREATE.code, fromRole: RoleCode.Client, toRole: null},
        {claim: module.FINANCIAL.claim.CREATE.code, fromRole: RoleCode.ProductManager, toRole: RoleCode.Client},
        {claim: module.FINANCIAL.claim.UPDATE.code, fromRole: RoleCode.ProductManager, toRole: RoleCode.Client},
        {claim: module.FINANCIAL.claim.UPDATE.code, fromRole: RoleCode.ProductAdmin, toRole: RoleCode.Client},
        {claim: module.FINANCIAL.claim.UPDATE.code, fromRole: RoleCode.Client, toRole: null},
        {claim: module.FINANCIAL.claim.DELETE.code, fromRole: RoleCode.Client, toRole: null},
        {claim: module.FINANCIAL.claim.DELETE.code, fromRole: RoleCode.ProductAdmin, toRole: RoleCode.Client},
        {claim: module.FINANCIAL.claim.DELETE.code, fromRole: RoleCode.ProductManager, toRole: RoleCode.Client},

        {claim: module.ACCOUNTING.claim.GET.code, fromRole: RoleCode.Client, toRole: null},
        {claim: module.ACCOUNTING.claim.GET.code, fromRole: RoleCode.ProductAdmin, toRole: RoleCode.Client},
        {claim: module.ACCOUNTING.claim.GET.code, fromRole: RoleCode.ProductManager, toRole: RoleCode.Client},
        {claim: module.ACCOUNTING.claim.CREATE.code, fromRole: RoleCode.ProductAdmin, toRole: RoleCode.Client},
        {claim: module.ACCOUNTING.claim.CREATE.code, fromRole: RoleCode.Client, toRole: null},
        {claim: module.ACCOUNTING.claim.CREATE.code, fromRole: RoleCode.ProductManager, toRole: RoleCode.Client},
        {claim: module.ACCOUNTING.claim.UPDATE.code, fromRole: RoleCode.Client, toRole: null},
        {claim: module.ACCOUNTING.claim.UPDATE.code, fromRole: RoleCode.ProductAdmin, toRole: RoleCode.Client},
        {claim: module.ACCOUNTING.claim.UPDATE.code, fromRole: RoleCode.ProductManager, toRole: RoleCode.Client},
        {claim: module.ACCOUNTING.claim.DELETE.code, fromRole: RoleCode.ProductAdmin, toRole: RoleCode.Client},
        {claim: module.ACCOUNTING.claim.DELETE.code, fromRole: RoleCode.Client, toRole: null},
        {claim: module.ACCOUNTING.claim.DELETE.code, fromRole: RoleCode.ProductManager, toRole: RoleCode.Client},

        {claim: module.ABN.claim.GET.code, fromRole: RoleCode.Client, toRole: null},

        {claim: module.LOG.claim.GET.code, fromRole: RoleCode.ProductAdmin, toRole: null},
        {claim: module.LOG.claim.GET.code, fromRole: RoleCode.Client, toRole: null},
        {claim: module.LOG.claim.GET.code, fromRole: RoleCode.ProductManager, toRole: RoleCode.Client},
        {claim: module.LOG.claim.GET.code, fromRole: RoleCode.ProductAdmin, toRole: RoleCode.Client},
        {claim: module.LOG.claim.GET.code, fromRole: RoleCode.ProductManager, toRole: null},
        {claim: module.LOG.claim.GET.code, fromRole: RoleCode.ProductAdmin, toRole: RoleCode.ProductManager},

        {claim: module.MENU.claim.TRANSACTION.code, fromRole: RoleCode.ProductManager, toRole: null},
        {claim: module.MENU.claim.TRANSACTION.code, fromRole: RoleCode.Client, toRole: null},
        {claim: module.MENU.claim.TRANSACTION.code, fromRole: RoleCode.ProductAdmin, toRole: null},
        {claim: module.MENU.claim.BUSINESS_DETAIL.code, fromRole: RoleCode.ProductAdmin, toRole: null},
        {claim: module.MENU.claim.BUSINESS_DETAIL.code, fromRole: RoleCode.ProductManager, toRole: null},
        {claim: module.MENU.claim.BUSINESS_DETAIL.code, fromRole: RoleCode.Client, toRole: null},
        {claim: module.MENU.claim.DASHBOARD.code, fromRole: RoleCode.ProductAdmin, toRole: null},
        {claim: module.MENU.claim.TEAM_MANAGEMENT.code, fromRole: RoleCode.ProductAdmin, toRole: null},
        {claim: module.MENU.claim.CLIENT_MANAGEMENT.code, fromRole: RoleCode.ProductAdmin, toRole: null},
        {claim: module.MENU.claim.CLIENT_MANAGEMENT.code, fromRole: RoleCode.ProductManager, toRole: null},
        {claim: module.MENU.claim.MESSAGE.code, fromRole: RoleCode.ProductAdmin, toRole: null},
        {claim: module.MENU.claim.MESSAGE.code, fromRole: RoleCode.ProductManager, toRole: null},
        {claim: module.MENU.claim.MESSAGE.code, fromRole: RoleCode.Client, toRole: null},
        {claim: module.MENU.claim.DATA_REPORT.code, fromRole: RoleCode.ProductAdmin, toRole: null},
        {claim: module.MENU.claim.SETTING.code, fromRole: RoleCode.ProductAdmin, toRole: null},

        {claim: module.BUDGET.claim.GET.code, fromRole: RoleCode.ProductAdmin, toRole: RoleCode.Client},
        {claim: module.BUDGET.claim.GET.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Client},
        {claim: module.BUDGET.claim.GET.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.Client},
        {claim: module.BUDGET.claim.GET.code, fromRole: RoleCode.Supervisor, toRole: RoleCode.Client},
        {claim: module.BUDGET.claim.GET.code, fromRole: RoleCode.CaseManager, toRole: RoleCode.Client},
        {claim: module.BUDGET.claim.CREATE.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Client},
        {claim: module.BUDGET.claim.CREATE.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.Client},
        {claim: module.BUDGET.claim.CREATE.code, fromRole: RoleCode.Supervisor, toRole: RoleCode.Client},
        {claim: module.BUDGET.claim.CREATE.code, fromRole: RoleCode.CaseManager, toRole: RoleCode.Client},
        {claim: module.BUDGET.claim.CREATE.code, fromRole: RoleCode.ProductAdmin, toRole: RoleCode.Client},

        {claim: module.CRUNCHER.claim.GET.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Client},
        {claim: module.CRUNCHER.claim.GET.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.Client},
        {claim: module.CRUNCHER.claim.GET.code, fromRole: RoleCode.Supervisor, toRole: RoleCode.Client},
        {claim: module.CRUNCHER.claim.GET.code, fromRole: RoleCode.CaseManager, toRole: RoleCode.Client},
        {claim: module.CRUNCHER.claim.GET.code, fromRole: RoleCode.ProductAdmin, toRole: RoleCode.Client},
        {claim: module.CRUNCHER.claim.UPDATE.code, fromRole: RoleCode.CaseManager, toRole: RoleCode.Client},
        {claim: module.CRUNCHER.claim.APPROVE.code, fromRole: RoleCode.Supervisor, toRole: RoleCode.Client},

        {claim: module.MESSAGE.claim.GET.code, fromRole: RoleCode.ProductAdmin, toRole: null},
        {claim: module.MESSAGE.claim.GET.code, fromRole: RoleCode.ProductManager, toRole: null},
        {claim: module.MESSAGE.claim.GET.code, fromRole: RoleCode.Client, toRole: null},

        {claim: module.REPORT.claim.GET.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Client},
        // {claim: module.REPORT.claim.GET.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.Client},
        // {claim: module.REPORT.claim.GET.code, fromRole: RoleCode.Supervisor, toRole: RoleCode.Client},
        // {claim: module.REPORT.claim.GET.code, fromRole: RoleCode.CaseManager, toRole: RoleCode.Client},
        {claim: module.REPORT.claim.GET.code, fromRole: RoleCode.ProductAdmin, toRole: RoleCode.Client},

        {claim: module.YODLEE.claim.GET.code, fromRole: RoleCode.Client, toRole: null},

        {claim: module.AUTOCRUNCHER.claim.GET.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Client},
        {claim: module.AUTOCRUNCHER.claim.GET.code, fromRole: RoleCode.CaseManager, toRole: RoleCode.Client},
        {claim: module.AUTOCRUNCHER.claim.CREATE.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Client},
        {claim: module.AUTOCRUNCHER.claim.CREATE.code, fromRole: RoleCode.CaseManager, toRole: RoleCode.Client},
        {claim: module.AUTOCRUNCHER.claim.DELETE.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Client},
        {claim: module.AUTOCRUNCHER.claim.DELETE.code, fromRole: RoleCode.CaseManager, toRole: RoleCode.Client},
        {claim: module.AUTOCRUNCHER.claim.UPDATE.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Client},
        {claim: module.AUTOCRUNCHER.claim.UPDATE.code, fromRole: RoleCode.CaseManager, toRole: RoleCode.Client},
    ];
};
