import module from 'justdone-system-package/dest/resources/permission/module';
import {RoleCode} from 'justdone-system-package/dest/app/model/common/CommonType';

export function getPermissions(): {claim: number, fromRole: number, toRole: number | null}[] {
    return [
        {claim: module.SYSTEM.claim.ACCESS.code, fromRole: RoleCode.SuperAdmin, toRole: null},
        {claim: module.SYSTEM.claim.ACCESS.code, fromRole: RoleCode.RegionAdmin, toRole: null},
        {claim: module.SYSTEM.claim.ACCESS.code, fromRole: RoleCode.Supervisor, toRole: null},
        {claim: module.SYSTEM.claim.ACCESS.code, fromRole: RoleCode.CaseManager, toRole: null},
        {claim: module.PRODUCT.claim.GET.code, fromRole: RoleCode.SuperAdmin, toRole: null},
        {claim: module.PRODUCT.claim.GET.code, fromRole: RoleCode.RegionAdmin, toRole: null},
        {claim: module.PRODUCT.claim.GET.code, fromRole: RoleCode.CaseManager, toRole: null},
        {claim: module.PRODUCT.claim.GET.code, fromRole: RoleCode.Supervisor, toRole: null},
        {claim: module.PRODUCT.claim.CREATE.code, fromRole: RoleCode.SuperAdmin, toRole: null},
        {claim: module.PRODUCT.claim.UPDATE.code, fromRole: RoleCode.SuperAdmin, toRole: null},
        {claim: module.PRODUCT.claim.UPDATE.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.ProductAdmin},
        {claim: module.PRODUCT.claim.DELETE.code, fromRole: RoleCode.SuperAdmin, toRole: null},
        {claim: module.ROLE.claim.GET.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.RegionAdmin},
        {claim: module.ROLE.claim.GET.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Supervisor},
        {claim: module.ROLE.claim.GET.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.CaseManager},
        {claim: module.ROLE.claim.GET.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.Supervisor},
        {claim: module.ROLE.claim.GET.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.CaseManager},
        {claim: module.ROLE.claim.GET.code, fromRole: RoleCode.Supervisor, toRole: RoleCode.CaseManager},
        {claim: module.ROLE.claim.CREATE.code, fromRole: RoleCode.SuperAdmin, toRole: null},
        {claim: module.ROLE.claim.UPDATE.code, fromRole: RoleCode.SuperAdmin, toRole: null},
        {claim: module.ROLE.claim.DELETE.code, fromRole: RoleCode.SuperAdmin, toRole: null},
        {claim: module.MANAGER.claim.GET.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.RegionAdmin},
        {claim: module.MANAGER.claim.GET.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Supervisor},
        {claim: module.MANAGER.claim.GET.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.CaseManager},
        {claim: module.MANAGER.claim.GET.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.Supervisor},
        {claim: module.MANAGER.claim.GET.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.CaseManager},
        {claim: module.MANAGER.claim.GET.code, fromRole: RoleCode.Supervisor, toRole: RoleCode.CaseManager},
        {claim: module.MANAGER.claim.GET.code, fromRole: RoleCode.ProductAdmin, toRole: RoleCode.Supervisor},
        {claim: module.MANAGER.claim.GET.code, fromRole: RoleCode.ProductManager, toRole: RoleCode.Supervisor},
        {claim: module.MANAGER.claim.GET_CLIENT.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.GET_CLIENT.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.GET_CLIENT.code, fromRole: RoleCode.Supervisor, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.GET_CLIENT.code, fromRole: RoleCode.CaseManager, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.GET_CLIENT_BY_MANAGER.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.ProductManager},
        {claim: module.MANAGER.claim.GET_CLIENT_BY_MANAGER.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.CaseManager},
        {claim: module.MANAGER.claim.GET_CLIENT_BY_MANAGER.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.Supervisor},
        {claim: module.MANAGER.claim.GET_CLIENT_BY_MANAGER.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.RegionAdmin},
        {claim: module.MANAGER.claim.GET_CLIENT_BY_MANAGER.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.CaseManager},
        {claim: module.MANAGER.claim.GET_CLIENT_BY_MANAGER.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.ProductManager},
        {claim: module.MANAGER.claim.GET_CLIENT_BY_MANAGER.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.ProductAdmin},
        {claim: module.MANAGER.claim.GET_CLIENT_BY_MANAGER.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Supervisor},
        {claim: module.MANAGER.claim.GET_CLIENT_BY_MANAGER.code, fromRole: RoleCode.Supervisor, toRole: RoleCode.ProductManager},
        {claim: module.MANAGER.claim.GET_CLIENT_BY_MANAGER.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.ProductAdmin},
        {claim: module.MANAGER.claim.GET_CLIENT_BY_MANAGER.code, fromRole: RoleCode.Supervisor, toRole: RoleCode.ProductAdmin},
        {claim: module.MANAGER.claim.GET_CLIENT_BY_MANAGER.code, fromRole: RoleCode.Supervisor, toRole: RoleCode.CaseManager},
        {claim: module.MANAGER.claim.GET_CLIENT_PERSONAL_INFO.code, fromRole: RoleCode.Supervisor, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.GET_CLIENT_PERSONAL_INFO.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.GET_CLIENT_PERSONAL_INFO.code, fromRole: RoleCode.CaseManager, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.GET_CLIENT_PERSONAL_INFO.code, fromRole: RoleCode.Supervisor, toRole: null},
        {claim: module.MANAGER.claim.GET_CLIENT_PERSONAL_INFO.code, fromRole: RoleCode.RegionAdmin, toRole: null},
        {claim: module.MANAGER.claim.GET_CLIENT_PERSONAL_INFO.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.GET_CLIENT_PERSONAL_INFO.code, fromRole: RoleCode.SuperAdmin, toRole: null},
        {claim: module.MANAGER.claim.GET_CLIENT_PERSONAL_INFO.code, fromRole: RoleCode.CaseManager, toRole: null},
        {claim: module.MANAGER.claim.GET_CLIENT_BUSINESS_INFO.code, fromRole: RoleCode.RegionAdmin, toRole: null},
        {claim: module.MANAGER.claim.GET_CLIENT_BUSINESS_INFO.code, fromRole: RoleCode.Supervisor, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.GET_CLIENT_BUSINESS_INFO.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.GET_CLIENT_BUSINESS_INFO.code, fromRole: RoleCode.Supervisor, toRole: null},
        {claim: module.MANAGER.claim.GET_CLIENT_BUSINESS_INFO.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.GET_CLIENT_BUSINESS_INFO.code, fromRole: RoleCode.CaseManager, toRole: null},
        {claim: module.MANAGER.claim.GET_CLIENT_BUSINESS_INFO.code, fromRole: RoleCode.SuperAdmin, toRole: null},
        {claim: module.MANAGER.claim.GET_CLIENT_BUSINESS_INFO.code, fromRole: RoleCode.CaseManager, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.GET_CLIENT_CONNECTED_BANK.code, fromRole: RoleCode.CaseManager, toRole: null},
        {claim: module.MANAGER.claim.GET_CLIENT_CONNECTED_BANK.code, fromRole: RoleCode.CaseManager, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.GET_CLIENT_CONNECTED_BANK.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.GET_CLIENT_CONNECTED_BANK.code, fromRole: RoleCode.Supervisor, toRole: null},
        {claim: module.MANAGER.claim.GET_CLIENT_CONNECTED_BANK.code, fromRole: RoleCode.SuperAdmin, toRole: null},
        {claim: module.MANAGER.claim.GET_CLIENT_CONNECTED_BANK.code, fromRole: RoleCode.Supervisor, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.GET_CLIENT_CONNECTED_BANK.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.GET_CLIENT_CONNECTED_BANK.code, fromRole: RoleCode.RegionAdmin, toRole: null},
        {claim: module.MANAGER.claim.GET_CLIENT_TRADING_QUESTION.code, fromRole: RoleCode.CaseManager, toRole: null},
        {claim: module.MANAGER.claim.GET_CLIENT_TRADING_QUESTION.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.GET_CLIENT_TRADING_QUESTION.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.GET_CLIENT_TRADING_QUESTION.code, fromRole: RoleCode.Supervisor, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.GET_CLIENT_TRADING_QUESTION.code, fromRole: RoleCode.CaseManager, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.GET_CLIENT_TRADING_QUESTION.code, fromRole: RoleCode.RegionAdmin, toRole: null},
        {claim: module.MANAGER.claim.GET_CLIENT_TRADING_QUESTION.code, fromRole: RoleCode.SuperAdmin, toRole: null},
        {claim: module.MANAGER.claim.GET_CLIENT_TRADING_QUESTION.code, fromRole: RoleCode.Supervisor, toRole: null},
        // {claim: module.MANAGER.claim.CREATE.code, fromRole: RoleCode.SuperAdmin, toRole: null},
        {claim: module.MANAGER.claim.CREATE.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.CaseManager},
        {claim: module.MANAGER.claim.CREATE.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.RegionAdmin},
        {claim: module.MANAGER.claim.CREATE.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.ProductManager},
        {claim: module.MANAGER.claim.CREATE.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.ProductAdmin},
        {claim: module.MANAGER.claim.CREATE.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Supervisor},
        {claim: module.MANAGER.claim.CREATE.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.Supervisor},
        {claim: module.MANAGER.claim.CREATE.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.CaseManager},
        {claim: module.MANAGER.claim.CREATE.code, fromRole: RoleCode.Supervisor, toRole: RoleCode.CaseManager},
        {claim: module.MANAGER.claim.CREATE_CLIENT.code, fromRole: RoleCode.Supervisor, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.CREATE_CLIENT.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.CREATE_CLIENT.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.CREATE_CLIENT.code, fromRole: RoleCode.SuperAdmin, toRole: null},
        // {claim: module.MANAGER.claim.INVITE_CLIENT.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.Client},
        // {claim: module.MANAGER.claim.INVITE_CLIENT.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Client},
        // {claim: module.MANAGER.claim.INVITE_CLIENT.code, fromRole: RoleCode.RegionAdmin, toRole: null},
        // {claim: module.MANAGER.claim.INVITE_CLIENT.code, fromRole: RoleCode.Supervisor, toRole: RoleCode.Client},
        // {claim: module.MANAGER.claim.INVITE_CLIENT.code, fromRole: RoleCode.SuperAdmin, toRole: null},
        {claim: module.MANAGER.claim.UPDATE.code, fromRole: RoleCode.CaseManager, toRole: null},
        {claim: module.MANAGER.claim.UPDATE.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.CaseManager},
        {claim: module.MANAGER.claim.UPDATE.code, fromRole: RoleCode.SuperAdmin, toRole: null},
        {claim: module.MANAGER.claim.UPDATE.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.CaseManager},
        {claim: module.MANAGER.claim.UPDATE.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.Supervisor},
        {claim: module.MANAGER.claim.UPDATE.code, fromRole: RoleCode.RegionAdmin, toRole: null},
        // {claim: module.MANAGER.claim.UPDATE.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.ProductAdmin},
        {claim: module.MANAGER.claim.UPDATE.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Supervisor},
        {claim: module.MANAGER.claim.UPDATE.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.RegionAdmin},
        // {claim: module.MANAGER.claim.UPDATE.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.ProductManager},
        {claim: module.MANAGER.claim.UPDATE.code, fromRole: RoleCode.Supervisor, toRole: null},
        {claim: module.MANAGER.claim.UPDATE.code, fromRole: RoleCode.Supervisor, toRole: RoleCode.CaseManager},
        {claim: module.MANAGER.claim.UPDATE_CLIENT.code, fromRole: RoleCode.Supervisor, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.UPDATE_CLIENT.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.UPDATE_CLIENT.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.UPDATE_CLIENT.code, fromRole: RoleCode.RegionAdmin, toRole: null},
        {claim: module.MANAGER.claim.UPDATE_CLIENT.code, fromRole: RoleCode.SuperAdmin, toRole: null},
        {claim: module.MANAGER.claim.UPDATE_CLIENT.code, fromRole: RoleCode.CaseManager, toRole: RoleCode.Client},
        // {claim: module.MANAGER.claim.UPDATE_CLIENT_PERSONAL_INFO.code, fromRole: RoleCode.RegionAdmin, toRole: null},
        // {claim: module.MANAGER.claim.UPDATE_CLIENT_PERSONAL_INFO.code, fromRole: RoleCode.SuperAdmin, toRole: null},
        // {claim: module.MANAGER.claim.UPDATE_CLIENT_PERSONAL_INFO.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.Client},
        // {claim: module.MANAGER.claim.UPDATE_CLIENT_PERSONAL_INFO.code, fromRole: RoleCode.Supervisor, toRole: RoleCode.Client},
        // {claim: module.MANAGER.claim.UPDATE_CLIENT_PERSONAL_INFO.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Client},
        // {claim: module.MANAGER.claim.UPDATE_CLIENT_PERSONAL_INFO.code, fromRole: RoleCode.CaseManager, toRole: RoleCode.Client},
        // {claim: module.MANAGER.claim.UPDATE_CLIENT_BUSINESS_INFO.code, fromRole: RoleCode.Supervisor, toRole: RoleCode.Client},
        // {claim: module.MANAGER.claim.UPDATE_CLIENT_BUSINESS_INFO.code, fromRole: RoleCode.RegionAdmin, toRole: null},
        // {claim: module.MANAGER.claim.UPDATE_CLIENT_BUSINESS_INFO.code, fromRole: RoleCode.CaseManager, toRole: RoleCode.Client},
        // {claim: module.MANAGER.claim.UPDATE_CLIENT_BUSINESS_INFO.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Client},
        // {claim: module.MANAGER.claim.UPDATE_CLIENT_BUSINESS_INFO.code, fromRole: RoleCode.SuperAdmin, toRole: null},
        // {claim: module.MANAGER.claim.UPDATE_CLIENT_BUSINESS_INFO.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.UPDATE_CLIENT_CONNECTED_BANK.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.UPDATE_CLIENT_CONNECTED_BANK.code, fromRole: RoleCode.RegionAdmin, toRole: null},
        {claim: module.MANAGER.claim.UPDATE_CLIENT_CONNECTED_BANK.code, fromRole: RoleCode.Supervisor, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.UPDATE_CLIENT_CONNECTED_BANK.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.UPDATE_CLIENT_CONNECTED_BANK.code, fromRole: RoleCode.SuperAdmin, toRole: null},
        {claim: module.MANAGER.claim.UPDATE_CLIENT_CONNECTED_BANK.code, fromRole: RoleCode.CaseManager, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.UPDATE_CLIENT_TRADING_QUESTION.code, fromRole: RoleCode.RegionAdmin, toRole: null},
        {claim: module.MANAGER.claim.UPDATE_CLIENT_TRADING_QUESTION.code, fromRole: RoleCode.SuperAdmin, toRole: null},

        {claim: module.MANAGER.claim.ASSIGN_MANAGER.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Supervisor},
        {claim: module.MANAGER.claim.ASSIGN_MANAGER.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.CaseManager},
        {claim: module.MANAGER.claim.ASSIGN_MANAGER.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.CaseManager},
        // {claim: module.MANAGER.claim.ASSIGN_MANAGER.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.ProductAdmin},
        {claim: module.MANAGER.claim.ASSIGN_MANAGER.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.ProductManager},
        {claim: module.MANAGER.claim.ASSIGN_MANAGER.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.ASSIGN_MANAGER.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.ASSIGN_MANAGER.code, fromRole: RoleCode.Supervisor, toRole: RoleCode.Client},
        // ++ add "Update-client-reconnect-bank"
        {claim: module.MANAGER.claim.UPDATE_CLIENT_RECONNECT_BANK.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.UPDATE_CLIENT_RECONNECT_BANK.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.UPDATE_CLIENT_RECONNECT_BANK.code, fromRole: RoleCode.Supervisor, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.UPDATE_CLIENT_RECONNECT_BANK.code, fromRole: RoleCode.CaseManager, toRole: RoleCode.Client},
        // -- add
        {claim: module.MANAGER.claim.DELETE.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.ProductAdmin},
        {claim: module.MANAGER.claim.DELETE.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.CaseManager},
        {claim: module.MANAGER.claim.DELETE.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.RegionAdmin},
        {claim: module.MANAGER.claim.DELETE.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.ProductManager},
        {claim: module.MANAGER.claim.DELETE.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Supervisor},
        // {claim: module.MANAGER.claim.DELETE_CLIENT.code, fromRole: RoleCode.RegionAdmin, toRole: null},
        {claim: module.MANAGER.claim.DELETE_CLIENT.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Client},
        {claim: module.MANAGER.claim.DELETE_CLIENT.code, fromRole: RoleCode.SuperAdmin, toRole: null},
        {claim: module.GROUP_EXPENSE.claim.GET.code, fromRole: RoleCode.RegionAdmin, toRole: null},
        {claim: module.GROUP_EXPENSE.claim.GET.code, fromRole: RoleCode.Supervisor, toRole: null},
        {claim: module.GROUP_EXPENSE.claim.GET.code, fromRole: RoleCode.SuperAdmin, toRole: null},
        {claim: module.GROUP_EXPENSE.claim.GET.code, fromRole: RoleCode.CaseManager, toRole: null},
        {claim: module.CHART_OF_ACCOUNT.claim.GET.code, fromRole: RoleCode.SuperAdmin, toRole: null},
        {claim: module.CHART_OF_ACCOUNT.claim.GET.code, fromRole: RoleCode.Supervisor, toRole: null},
        {claim: module.CHART_OF_ACCOUNT.claim.GET.code, fromRole: RoleCode.CaseManager, toRole: null},
        {claim: module.CHART_OF_ACCOUNT.claim.GET.code, fromRole: RoleCode.RegionAdmin, toRole: null},
        // ++ add assign client to COA
        {claim: module.CHART_OF_ACCOUNT.claim.ASSIGN_CLIENT.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Client},
        // - add
        {claim: module.CHART_OF_ACCOUNT.claim.CREATE.code, fromRole: RoleCode.SuperAdmin, toRole: null},
        {claim: module.CHART_OF_ACCOUNT.claim.UPDATE.code, fromRole: RoleCode.SuperAdmin, toRole: null},
        {claim: module.CHART_OF_ACCOUNT.claim.DELETE.code, fromRole: RoleCode.SuperAdmin, toRole: null},
        {claim: module.STATEMENT.claim.GET.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.Client},
        {claim: module.STATEMENT.claim.GET.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Client},
        {claim: module.STATEMENT.claim.GET.code, fromRole: RoleCode.CaseManager, toRole: RoleCode.Client},
        {claim: module.STATEMENT.claim.GET.code, fromRole: RoleCode.Supervisor, toRole: RoleCode.Client},
        {claim: module.STATEMENT.claim.UPDATE.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.Client},
        {claim: module.STATEMENT.claim.UPDATE.code, fromRole: RoleCode.CaseManager, toRole: RoleCode.Client},
        {claim: module.STATEMENT.claim.UPDATE.code, fromRole: RoleCode.Supervisor, toRole: RoleCode.Client},
        {claim: module.STATEMENT.claim.UPDATE.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Client},
        {claim: module.TRANSACTION.claim.GET.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.Client},
        {claim: module.TRANSACTION.claim.GET.code, fromRole: RoleCode.Supervisor, toRole: RoleCode.Client},
        {claim: module.TRANSACTION.claim.GET.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Client},
        {claim: module.TRANSACTION.claim.GET.code, fromRole: RoleCode.CaseManager, toRole: RoleCode.Client},
        {claim: module.PROVIDER.claim.GET.code, fromRole: RoleCode.Supervisor, toRole: RoleCode.Client},
        {claim: module.PROVIDER.claim.GET.code, fromRole: RoleCode.CaseManager, toRole: RoleCode.Client},
        {claim: module.PROVIDER.claim.GET.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Client},
        {claim: module.PROVIDER.claim.GET.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.Client},
        {claim: module.RECEIPT.claim.GET.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Client},
        {claim: module.RECEIPT.claim.GET.code, fromRole: RoleCode.CaseManager, toRole: RoleCode.Client},
        {claim: module.RECEIPT.claim.GET.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.Client},
        {claim: module.RECEIPT.claim.GET.code, fromRole: RoleCode.Supervisor, toRole: RoleCode.Client},
        {claim: module.RECEIPT.claim.CREATE.code, fromRole: RoleCode.CaseManager, toRole: RoleCode.Client},
        {claim: module.RECEIPT.claim.CREATE.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Client},
        {claim: module.RECEIPT.claim.CREATE.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.Client},
        {claim: module.RECEIPT.claim.CREATE.code, fromRole: RoleCode.Supervisor, toRole: RoleCode.Client},
        {claim: module.RECEIPT.claim.UPDATE.code, fromRole: RoleCode.CaseManager, toRole: RoleCode.Client},
        {claim: module.RECEIPT.claim.UPDATE.code, fromRole: RoleCode.Supervisor, toRole: RoleCode.Client},
        {claim: module.RECEIPT.claim.UPDATE.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.Client},
        {claim: module.RECEIPT.claim.UPDATE.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Client},
        {claim: module.RECEIPT.claim.DELETE.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Client},
        {claim: module.RECEIPT.claim.DELETE.code, fromRole: RoleCode.CaseManager, toRole: RoleCode.Client},
        {claim: module.RECEIPT.claim.DELETE.code, fromRole: RoleCode.Supervisor, toRole: RoleCode.Client},
        {claim: module.RECEIPT.claim.DELETE.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.Client},
        {claim: module.FINANCIAL.claim.GET.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.Client},
        {claim: module.FINANCIAL.claim.GET.code, fromRole: RoleCode.Supervisor, toRole: RoleCode.Client},
        {claim: module.FINANCIAL.claim.GET.code, fromRole: RoleCode.CaseManager, toRole: RoleCode.Client},
        {claim: module.FINANCIAL.claim.GET.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Client},
        {claim: module.FINANCIAL.claim.CREATE.code, fromRole: RoleCode.CaseManager, toRole: RoleCode.Client},
        {claim: module.FINANCIAL.claim.CREATE.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Client},
        {claim: module.FINANCIAL.claim.CREATE.code, fromRole: RoleCode.Supervisor, toRole: RoleCode.Client},
        {claim: module.FINANCIAL.claim.CREATE.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.Client},
        {claim: module.FINANCIAL.claim.UPDATE.code, fromRole: RoleCode.Supervisor, toRole: RoleCode.Client},
        {claim: module.FINANCIAL.claim.UPDATE.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.Client},
        {claim: module.FINANCIAL.claim.UPDATE.code, fromRole: RoleCode.CaseManager, toRole: RoleCode.Client},
        {claim: module.FINANCIAL.claim.UPDATE.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Client},
        {claim: module.FINANCIAL.claim.DELETE.code, fromRole: RoleCode.CaseManager, toRole: RoleCode.Client},
        {claim: module.FINANCIAL.claim.DELETE.code, fromRole: RoleCode.Supervisor, toRole: RoleCode.Client},
        {claim: module.FINANCIAL.claim.DELETE.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.Client},
        {claim: module.FINANCIAL.claim.DELETE.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Client},
        {claim: module.ACCOUNTING.claim.GET.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.Client},
        {claim: module.ACCOUNTING.claim.GET.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Client},
        {claim: module.ACCOUNTING.claim.GET.code, fromRole: RoleCode.CaseManager, toRole: RoleCode.Client},
        {claim: module.ACCOUNTING.claim.GET.code, fromRole: RoleCode.Supervisor, toRole: RoleCode.Client},
        {claim: module.ACCOUNTING.claim.CREATE.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.Client},
        {claim: module.ACCOUNTING.claim.CREATE.code, fromRole: RoleCode.Supervisor, toRole: RoleCode.Client},
        {claim: module.ACCOUNTING.claim.CREATE.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Client},
        {claim: module.ACCOUNTING.claim.CREATE.code, fromRole: RoleCode.CaseManager, toRole: RoleCode.Client},
        {claim: module.ACCOUNTING.claim.UPDATE.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Client},
        {claim: module.ACCOUNTING.claim.UPDATE.code, fromRole: RoleCode.CaseManager, toRole: RoleCode.Client},
        {claim: module.ACCOUNTING.claim.UPDATE.code, fromRole: RoleCode.Supervisor, toRole: RoleCode.Client},
        {claim: module.ACCOUNTING.claim.UPDATE.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.Client},
        {claim: module.ACCOUNTING.claim.DELETE.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.Client},
        {claim: module.ACCOUNTING.claim.DELETE.code, fromRole: RoleCode.Supervisor, toRole: RoleCode.Client},
        {claim: module.ACCOUNTING.claim.DELETE.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Client},
        {claim: module.ACCOUNTING.claim.DELETE.code, fromRole: RoleCode.CaseManager, toRole: RoleCode.Client},
        {claim: module.LOG.claim.GET.code, fromRole: RoleCode.Supervisor, toRole: RoleCode.Client},
        {claim: module.LOG.claim.GET.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.ProductManager},
        {claim: module.LOG.claim.GET.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Supervisor},
        {claim: module.LOG.claim.GET.code, fromRole: RoleCode.CaseManager, toRole: RoleCode.Client},
        {claim: module.LOG.claim.GET.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.ProductAdmin},
        {claim: module.LOG.claim.GET.code, fromRole: RoleCode.Supervisor, toRole: null},
        {claim: module.LOG.claim.GET.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.Client},
        {claim: module.LOG.claim.GET.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.Supervisor},
        {claim: module.LOG.claim.GET.code, fromRole: RoleCode.CaseManager, toRole: null},
        {claim: module.LOG.claim.GET.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Client},
        {claim: module.LOG.claim.GET.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.RegionAdmin},
        {claim: module.LOG.claim.GET.code, fromRole: RoleCode.RegionAdmin, toRole: null},
        {claim: module.LOG.claim.GET.code, fromRole: RoleCode.SuperAdmin, toRole: null},
        {claim: module.LOG.claim.GET.code, fromRole: RoleCode.Supervisor, toRole: RoleCode.CaseManager},
        {claim: module.LOG.claim.GET.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.CaseManager},
        {claim: module.LOG.claim.GET.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.CaseManager},
        {claim: module.MENU.claim.TRANSACTION.code, fromRole: RoleCode.SuperAdmin, toRole: null},
        {claim: module.MENU.claim.TRANSACTION.code, fromRole: RoleCode.Supervisor, toRole: null},
        {claim: module.MENU.claim.TRANSACTION.code, fromRole: RoleCode.CaseManager, toRole: null},
        {claim: module.MENU.claim.TRANSACTION.code, fromRole: RoleCode.RegionAdmin, toRole: null},
        {claim: module.MENU.claim.BUSINESS_DETAIL.code, fromRole: RoleCode.RegionAdmin, toRole: null},
        {claim: module.MENU.claim.BUSINESS_DETAIL.code, fromRole: RoleCode.SuperAdmin, toRole: null},
        {claim: module.MENU.claim.BUSINESS_DETAIL.code, fromRole: RoleCode.CaseManager, toRole: null},
        {claim: module.MENU.claim.BUSINESS_DETAIL.code, fromRole: RoleCode.Supervisor, toRole: null},
        {claim: module.MENU.claim.DASHBOARD.code, fromRole: RoleCode.Supervisor, toRole: null},
        {claim: module.MENU.claim.DASHBOARD.code, fromRole: RoleCode.RegionAdmin, toRole: null},
        {claim: module.MENU.claim.DASHBOARD.code, fromRole: RoleCode.SuperAdmin, toRole: null},
        {claim: module.MENU.claim.PRODUCT_MANAGEMENT.code, fromRole: RoleCode.SuperAdmin, toRole: null},
        {claim: module.MENU.claim.TEAM_MANAGEMENT.code, fromRole: RoleCode.RegionAdmin, toRole: null},
        {claim: module.MENU.claim.TEAM_MANAGEMENT.code, fromRole: RoleCode.SuperAdmin, toRole: null},
        {claim: module.MENU.claim.TEAM_MANAGEMENT.code, fromRole: RoleCode.Supervisor, toRole: null},
        {claim: module.MENU.claim.CLIENT_MANAGEMENT.code, fromRole: RoleCode.Supervisor, toRole: null},
        {claim: module.MENU.claim.CLIENT_MANAGEMENT.code, fromRole: RoleCode.RegionAdmin, toRole: null},
        {claim: module.MENU.claim.CLIENT_MANAGEMENT.code, fromRole: RoleCode.CaseManager, toRole: null},
        {claim: module.MENU.claim.CLIENT_MANAGEMENT.code, fromRole: RoleCode.SuperAdmin, toRole: null},
        {claim: module.MENU.claim.MESSAGE.code, fromRole: RoleCode.RegionAdmin, toRole: null},
        {claim: module.MENU.claim.MESSAGE.code, fromRole: RoleCode.SuperAdmin, toRole: null},
        {claim: module.MENU.claim.MESSAGE.code, fromRole: RoleCode.CaseManager, toRole: null},
        {claim: module.MENU.claim.MESSAGE.code, fromRole: RoleCode.Supervisor, toRole: null},
        {claim: module.MENU.claim.SERVER_INFORMATION.code, fromRole: RoleCode.SuperAdmin, toRole: null},
        {claim: module.MENU.claim.DATA_REPORT.code, fromRole: RoleCode.SuperAdmin, toRole: null},
        // {claim: module.MENU.claim.DATA_REPORT.code, fromRole: RoleCode.Supervisor, toRole: null},
        // {claim: module.MENU.claim.DATA_REPORT.code, fromRole: RoleCode.RegionAdmin, toRole: null},
        {claim: module.MENU.claim.CHART_OF_ACCOUNT.code, fromRole: RoleCode.SuperAdmin, toRole: null},
        {claim: module.MENU.claim.AUTOMATION_CRUNCH.code, fromRole: RoleCode.SuperAdmin, toRole: null},
        {claim: module.MENU.claim.AUTOMATION_CRUNCH.code, fromRole: RoleCode.CaseManager, toRole: null},
        {claim: module.MENU.claim.SETTING.code, fromRole: RoleCode.SuperAdmin, toRole: null},
        // add buget
        // ++ add
        {claim: module.BUDGET.claim.GET.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Client},
        {claim: module.BUDGET.claim.GET.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.Client},
        {claim: module.BUDGET.claim.GET.code, fromRole: RoleCode.Supervisor, toRole: RoleCode.Client},
        {claim: module.BUDGET.claim.GET.code, fromRole: RoleCode.CaseManager, toRole: RoleCode.Client},
        {claim: module.BUDGET.claim.CREATE.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Client},
        {claim: module.BUDGET.claim.CREATE.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.Client},
        {claim: module.BUDGET.claim.CREATE.code, fromRole: RoleCode.Supervisor, toRole: RoleCode.Client},
        {claim: module.BUDGET.claim.CREATE.code, fromRole: RoleCode.CaseManager, toRole: RoleCode.Client},
        // -- add
        // add cruncher
        {claim: module.CRUNCHER.claim.GET.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Client},
        {claim: module.CRUNCHER.claim.GET.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.Client},
        {claim: module.CRUNCHER.claim.GET.code, fromRole: RoleCode.Supervisor, toRole: RoleCode.Client},
        {claim: module.CRUNCHER.claim.GET.code, fromRole: RoleCode.CaseManager, toRole: RoleCode.Client},
        {claim: module.CRUNCHER.claim.UPDATE.code, fromRole: RoleCode.CaseManager, toRole: RoleCode.Client},
        {claim: module.CRUNCHER.claim.APPROVE.code, fromRole: RoleCode.Supervisor, toRole: RoleCode.Client},
        // -- add
        // add Message
        {claim: module.MESSAGE.claim.GET.code, fromRole: RoleCode.SuperAdmin, toRole: null},
        {claim: module.MESSAGE.claim.GET.code, fromRole: RoleCode.RegionAdmin, toRole: null},
        {claim: module.MESSAGE.claim.GET.code, fromRole: RoleCode.Supervisor, toRole: null},
        {claim: module.MESSAGE.claim.GET.code, fromRole: RoleCode.CaseManager, toRole: null},
        {claim: module.MESSAGE.claim.CREATE.code, fromRole: RoleCode.SuperAdmin, toRole: null},
        {claim: module.REPORT.claim.GET.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.Client},
        // {claim: module.REPORT.claim.GET.code, fromRole: RoleCode.RegionAdmin, toRole: RoleCode.Client},
        // {claim: module.REPORT.claim.GET.code, fromRole: RoleCode.Supervisor, toRole: RoleCode.Client},
        // {claim: module.REPORT.claim.GET.code, fromRole: RoleCode.CaseManager, toRole: RoleCode.Client},
        // -- add
        // ++ add auto cruncher
        {claim: module.AUTOCRUNCHER.claim.GET.code, fromRole: RoleCode.SuperAdmin, toRole: null},
        {claim: module.AUTOCRUNCHER.claim.GET.code, fromRole: RoleCode.CaseManager, toRole: null},
        {claim: module.AUTOCRUNCHER.claim.GET_MANAGER.code, fromRole: RoleCode.SuperAdmin, toRole: RoleCode.CaseManager},
        {claim: module.AUTOCRUNCHER.claim.CREATE.code, fromRole: RoleCode.SuperAdmin, toRole: null},
        {claim: module.AUTOCRUNCHER.claim.CREATE.code, fromRole: RoleCode.CaseManager, toRole: null},
        {claim: module.AUTOCRUNCHER.claim.UPDATE.code, fromRole: RoleCode.SuperAdmin, toRole: null},
        {claim: module.AUTOCRUNCHER.claim.UPDATE.code, fromRole: RoleCode.CaseManager, toRole: null},
        {claim: module.AUTOCRUNCHER.claim.DELETE.code, fromRole: RoleCode.SuperAdmin, toRole: null},
        {claim: module.AUTOCRUNCHER.claim.DELETE.code, fromRole: RoleCode.CaseManager, toRole: null},
        // -- add
    ];
};
